# Site settings
author: ARIF CAGIRICI
title: A.C.'S FLATRION BLOG
header-img: img/home-bg.png
email: acagirici23@gmail.com
copyright_name: ARIF CAGIRICI
description: > # this means to ignore newlines until "baseurl:"
  AC'S BLOG
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  acagirici

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
